-- Focus Forest: one tree per completed 45-minute focus round
create table if not exists public.focus_forest (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  planted_at timestamptz not null default now(),
  plant_date date not null default current_date,
  task_key text,
  task_title text not null default '自由專注',
  subject text not null default '自由專注',
  tree_type text not null default 'other' check (tree_type in ('math','physics','chemistry','biology','other')),
  focus_minutes integer not null default 45 check (focus_minutes between 1 and 180)
);

create index if not exists focus_forest_user_planted_idx
  on public.focus_forest (user_id, planted_at desc);

alter table public.focus_forest enable row level security;
grant select, insert, update, delete on table public.focus_forest to authenticated;

drop policy if exists "focus_forest_select_own" on public.focus_forest;
create policy "focus_forest_select_own" on public.focus_forest
  for select using (auth.uid() = user_id);

drop policy if exists "focus_forest_insert_own" on public.focus_forest;
create policy "focus_forest_insert_own" on public.focus_forest
  for insert with check (auth.uid() = user_id);

drop policy if exists "focus_forest_update_own" on public.focus_forest;
create policy "focus_forest_update_own" on public.focus_forest
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "focus_forest_delete_own" on public.focus_forest;
create policy "focus_forest_delete_own" on public.focus_forest
  for delete using (auth.uid() = user_id);

