const SCHOOL_ENDPOINT='https://www.thsh.tp.edu.tw/nss/site/thsh/storage/5eaaa09ffd724105bd1cf2c9/k2o0mq60853/find';
const SCHOOL_PAGE='https://www.thsh.tp.edu.tw/nss/s/thsh/111?g=c0dgl5fea8&&c=36owskn1cv';
const CLASS_TAG='36owskn1cv';
const GRADE_TAG='c0dgl5fea8';

function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':status===200?'public, max-age=120':'no-store','x-content-type-options':'nosniff'}})}
function stableKey(value){let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return`thsh-${(hash>>>0).toString(36)}`}
function subjectFor(text='',subTag=''){const known={c6gxyahgik:'英文',tpetdoiv7:'數學',lzexqbi3f7:'物理','66p4x60ej8':'公民',oga07h6w4:'化學',f1u5gdyusl:'地科',v65bqzzmj:'國文','53gnq965uo':'國文',mor8vq8ozf:'生物'};if(known[subTag])return known[subTag];const rules=[['物理',/物理/],['化學',/化學|化\d|化[一二三四五六七八九十]/],['生物',/生物|心搏|遺傳|細胞/],['英文',/英文|英聽|英U|單字|翻譯/],['國文',/國文|國寫|作文|成語/],['公民',/公民/],['地理',/地理/],['歷史',/歷史/],['地科',/地科/],['數學',/數學|數習|對話式|月考王/]];return rules.find(([,pattern])=>pattern.test(text))?.[0]||'班務'}
function safeLink(value){try{const url=new URL(value);return url.protocol==='https:'?url.href:''}catch{return''}}
function normalize(data,sourceDate){const groups=[['todayHW','今日交代功課'],['tomorrowTest','明日／近期考試'],['tomorrowBring','明日攜帶'],['teacherSay','老師叮嚀']],items=[];for(const [category,categoryLabel] of groups){for(const [index,item] of (Array.isArray(data?.[category])?data[category]:[]).entries()){if(item?.isDraft||!String(item?.text||'').trim())continue;const title=String(item.text).trim();items.push({key:stableKey(`${sourceDate}|${category}|${index}|${title}`),category,categoryLabel,subject:subjectFor(title,item.subTag),title,link:safeLink(item.link||'')})}}return items}
async function homework(request){const url=new URL(request.url),date=url.searchParams.get('date')||new Date().toISOString().slice(0,10);if(!/^20\d{2}-\d{2}-\d{2}$/.test(date))return json({error:'日期格式錯誤'},400);const sourceDate=date.replaceAll('-','/'),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),9000);try{const response=await fetch(SCHOOL_ENDPOINT,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({option:{query:[{match:{date:sourceDate,classTag:CLASS_TAG,gradeTag:GRADE_TAG}}]},vector:'private',static:false}),signal:controller.signal});if(!response.ok)throw new Error(`school ${response.status}`);const payload=await response.json(),data=payload?.data?.result?.[0]?.data||null;return json({source:'再興中學高二愛班電子聯絡簿',sourceUrl:SCHOOL_PAGE,sourceDate:date,lastUpdated:data?.lastUseTime||'',items:normalize(data,date)})}catch(error){return json({error:error?.name==='AbortError'?'學校網站回應逾時':'暫時無法讀取學校聯絡簿'},502)}finally{clearTimeout(timeout)}}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/homework'){if(request.method!=='GET')return json({error:'只支援 GET'},405);return homework(request)}if(env?.ASSETS?.fetch)return env.ASSETS.fetch(request);return new Response('Not found',{status:404})}};

